### ISSUE TITLE
Colormap error in 2d visualization

### ISSUE THREAD

**Issue by JeisonPacateque** [JeisonPacateque/Asphalt-Mixtures-Aging-Simulator#15]
The colormaps presents four color in the visualization , instead of the three corresponding to arvoids, aggregates, and mastic.

**Comment by mpuertog** [comment]
The 4th color represent the applied mask with value -1

**Comment by JeisonPacateque** [comment]
The user expectes a 3-phase segmentation.

**Comment by mpuertog** [comment]
The need of the filter through a mask is a client requirement

On Tue, Mar 3, 2015 at 2:05 PM, Jeison Pacateque <notifications@github.com>
wrote:

> The user expectes a 3-phase segmentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JeisonPacateque/Asphalt-Mixtures-Aging-Simulator/issues/15#issuecomment-77011555>
> .
>



-- 
--
Miguel Santiago Puerto

**Comment by mpuertog** [comment]
* Non-documented requirement...

On Tue, Mar 3, 2015 at 6:03 PM, Santiago Puerto <hibikimsp@gmail.com> wrote:

> The need of the filter through a mask is a client requirement
>
> On Tue, Mar 3, 2015 at 2:05 PM, Jeison Pacateque <notifications@github.com
> > wrote:
>
>> The user expectes a 3-phase segmentation.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JeisonPacateque/Asphalt-Mixtures-Aging-Simulator/issues/15#issuecomment-77011555>
>> .
>>
>
>
>
> --
> --
> Miguel Santiago Puerto
>



-- 
--
Miguel Santiago Puerto

**Comment by JeisonPacateque** [comment]
Fixed. Please, test it in 3d visualization (Mayavi)
