### ISSUE TITLE
Progress bar needed

### ISSUE THREAD

**Issue by JeisonPacateque** [JeisonPacateque/Asphalt-Mixtures-Aging-Simulator#4]
For the segmentation process and the simulation, it'd be nice to have a progress bar while the proccesses execute.

**Comment by hibikimsp** [comment]
Working on that...

**Comment by JeisonPacateque** [comment]
A first attemp to solve this was pushed in a branch. Please tes it. i'm not satisfied with the results, but it's something.

**Comment by JeisonPacateque** [comment]
I came acros with this solution, I'm gonna try to implement something similar https://gist.github.com/JeisonPacateque/7265bf7fc52654d29f1b

**Comment by JeisonPacateque** [comment]
Solved
