### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by JeisonPacateque** [JeisonPacateque/Asphalt-Mixtures-Aging-Simulator#8]
It is necessary to define a licence of software having clear the differences between GPL, MIT, BSD, LGPL, etc., keeping in mind the restrictions of the libraries used in the project

**Comment by hibikimsp** [comment]
Lets choose... http://choosealicense.com/licenses/

**Comment by mpuertog** [comment]
GPL 3.0 licence added.
